Develop
fursov231/java-explore-with-me pull request #1
Opened 2022-10-09 13:47 UTC by fursov231

2022-10-10 17:38 UTC, damirovna requested changes

2022-10-10 17:38 UTC, damirovna commented on ewm/src/main/java/ru/practicum/ewm/compilation/model/Compilation.java
> +
[Можно лучше]

Попробуйте добавить поле 

private List<Event> events;

с помощью join c compilations_events

Тогда и jdbc не понадобится в Сервисе

2022-10-10 17:38 UTC, damirovna commented on ewm/src/main/java/ru/practicum/ewm/compilation/dto/CompilationDto.java
> +    String title;
[Нужно исправить]

Нужно добавить аннотации @notblank и @SiZe

2022-10-10 17:38 UTC, damirovna commented on ewm/src/main/java/ru/practicum/ewm/compilation/dto/NewCompilationDto.java
> +    private String title;
[Нужно исправить]

Нужно добавить аннотации @notblank и @SiZe

2022-10-10 17:38 UTC, damirovna commented on ewm/src/main/java/ru/practicum/ewm/event/controller/EventController.java
> +public class EventController {
[Можно лучше]

Замечание аналогичное предыдущему, можно разбить контроллеры по доступу

2022-10-10 17:38 UTC, damirovna commented on ewm/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    private String state;
[Можно лучше]

Можно добавить аннотацию  @Enumerated(EnumType.STRING) и изменить тип поля на EventState

2022-10-10 17:38 UTC, damirovna commented on ewm/src/main/java/ru/practicum/ewm/event/dto/UpdateEventRequest.java
> +public class UpdateEventRequest {
[Нужно исправить]

Нужно добавить аннотации @NullOrNotBlank и @Size к полям:

- annotation
- description
- title

2022-10-10 17:38 UTC, damirovna commented on ewm/src/main/java/ru/practicum/ewm/event/dto/UpdateEventRequest.java
> +    private LocalDateTime eventDate;
[Нужно исправить]

Нужна аннотация, проверяющая, что событие начнётся в будущем

2022-10-10 17:38 UTC, damirovna commented on ewm/src/main/java/ru/practicum/ewm/event/dto/NewEventDto.java
> +public class NewEventDto {
[Нужно исправить]

Нужно добавить те же аннотации что и в UpdateEventRequest

2022-10-10 17:38 UTC, damirovna commented on ewm/src/main/java/ru/practicum/ewm/event/dto/EventFullDto.java
> +public class EventFullDto {
[Можно лучше]

В EventFullDto и EventShortDto дублируется код, это можно рещить с помощью базовых принципов ООП

2022-10-10 17:38 UTC, damirovna commented on ewm/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +                    rangeEnd, onlyAvailable, String.valueOf(sort), pageRequest)));
[Нужно исправить]

**_Просмотры нужно получать из сервиса статистики, это требование ТЗ_**

2022-10-10 17:38 UTC, damirovna commented on ewm/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +public class EventServiceImpl implements EventService {
[Можно лучше]

Во всех сервисах лучше добавить логгирование

2022-10-10 17:38 UTC, damirovna commented on ewm/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +        Optional<Event> event = eventRepository.findById(id);
[Можно лучше]

Вместо конструкции if - else можно использовать eventRepository.findById(id)
                .orElseThrow(...

2022-10-10 17:38 UTC, damirovna commented on ewm/src/main/java/ru/practicum/ewm/user/model/User.java
> +    private String email;
[Нужно исправить]

Нужно добавить 
@Column(length = ___, unique = true)

2022-10-10 17:38 UTC, damirovna commented on ewm/src/main/java/ru/practicum/ewm/user/dto/NewUserRequest.java
> +    String email;
[Нужно исправить]

Нужно добавить аннотацию @Email

2022-10-10 17:38 UTC, damirovna commented on ewm/src/main/java/ru/practicum/ewm/user/dto/NewUserRequest.java
> +    String name;
[Нужно исправить]

Нужно добавить аннотации @notblank и @SiZe

2022-10-10 17:38 UTC, damirovna commented on ewm/src/main/java/ru/practicum/ewm/user/dto/UserDto.java
> +    String name;
[Нужно исправить]

Нужно добавить аннотации @notblank и @SiZe

2022-10-11 14:33 UTC, fursov231 commented on ewm/src/main/java/ru/practicum/ewm/compilation/repository/jdbc/JdbCompilationsEventsDao.java
> +    public void saveCompilation(long compId, long eventId) {
Потому что мне нужно сохранять значения в соединительную таблицу compilations_events, а не в compilations,  к которому привязан интерфейс compilationRepository

2022-10-11 14:34 UTC, fursov231 commented on ewm/src/main/java/ru/practicum/ewm/compilation/repository/jdbc/JdbCompilationsEventsDao.java
> +    public List<Long> findEventIdByCompilationId(long compilationId) {
Потому что мне нужно получать список id из соединительной таблицы compilations_events, а не из compilations, к которому привязан compilationRepository

2022-10-11 19:21 UTC, fursov231 commented on ewm/src/main/java/ru/practicum/ewm/compilation/repository/jdbc/JdbCompilationsEventsDao.java
> +    public List<Long> findEventIdByCompilationId(long compilationId) {
upd: исправил по согласно следующему комментарию

2022-10-11 19:21 UTC, fursov231 commented on ewm/src/main/java/ru/practicum/ewm/compilation/repository/jdbc/JdbCompilationsEventsDao.java
> +    public void saveCompilation(long compId, long eventId) {
upd: исправил по согласно следующему комментарию

2022-10-12 14:37 UTC, damirovna approved these changes
Все измения внесены!

Отличная работа! Поздравляю!

2022-10-12 18:04 UTC, merged